# bind an address of this host
# empty for bind all addresses of this host
bind_addr =

# the exporter listen port
# the default value is 9898
port = 9898

# the FastDFS client config filename
fdfs_client_cfg = /etc/fdfs/client.conf

# daemon mode
# the default value is false
daemon = true


[auth]
# auth method, values:
##  none:  no auth
##  basic: HTTP basic auth
# the default value is none
# empty for no auth
method = none

# username for HTTP basic auth
# can't be empty when method is basic
username = test

# password for HTTP basic auth
# can't be empty when method is basic
password = hello1234
